language: cpp
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.5
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - libconfig++8-dev
    - gdb
    - gcc-4.9
    - g++-4.9
    - gcc-4.9-multilib
    - g++-4.9-multilib
    - gcc-multilib
    - g++-multilib
    - linux-libc-dev:i386
    - libcurl3:i386
    - libedit2
    - libedit-dev
    - llvm-3.5
    - llvm-3.5-dev
    - llvm-3.6
    - llvm-3.6-dev
    - llvm-3.7
    - llvm-3.7-dev
    - llvm-3.8
    - llvm-3.8-dev
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-4.9"; export CXX="g++-4.9"; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; brew install llvm36; brew install libconfig; fi;
env:
  - LLVM_CONFIG="llvm-config-3.7" OPTS="-DMULTILIB=ON"
  - LLVM_CONFIG="llvm-config-3.6" OPTS="-DBUILD_SHARED_LIBS=ON"
  - LLVM_CONFIG="llvm-config-3.6"
  - LLVM_CONFIG="llvm-config-3.5" OPTS="-DTEST_COVERAGE=ON"
  - LLVM_CONFIG="llvm-config-3.8"
matrix:
  allow_failures:
    - env: LLVM_CONFIG="llvm-config-3.8"
    - os: osx
      env: LLVM_CONFIG="llvm-config-3.6"
  exclude:
    - os: linux
      env: LLVM_CONFIG="llvm-config-3.6"
    - os: osx
      env: LLVM_CONFIG="llvm-config-3.7" OPTS="-DMULTILIB=ON"
    - os: osx
      env: LLVM_CONFIG="llvm-config-3.6" OPTS="-DBUILD_SHARED_LIBS=ON"
    - os: osx
      env: LLVM_CONFIG="llvm-config-3.5" OPTS="-DTEST_COVERAGE=ON"
    - os: osx
      env: LLVM_CONFIG="llvm-config-3.8"
script:
  - cmake -DLLVM_CONFIG=$(which ${LLVM_CONFIG}) $OPTS .
  - make -j3
  # Outputs some environment info, plus makes sure we only run the test suite
  # if we could actually build the executable.
  - bin/ldc2 -version || exit 1
  - MAKEOPTS=-j2 ctest -j1 --verbose -R "build-phobos2-" -E "-test-runner"
  - ctest -j3 --verbose -R "(build-)" -E "(build-phobos2-|-test-runner)"
  - CC="" MAKEOPTS=-j4 ctest -j1 --verbose -R "dmd-testsuite" -E "-debug"
  - CC="" MAKEOPTS=-j4 ctest -j1 --verbose -R "dmd-testsuite-debug"
  - ctest -j4 --output-on-failure -E "dmd-testsuite"

after_success:
  -
    if [[ "${OPTS}" == *TEST_COVERAGE*ON* ]]; then
      coveralls -e runtime -e tests -e vcbuild --gcov gcov-4.9 --gcov-options '\-lp' > /dev/null 2>&1;
    fi

notifications:
  email:
    recipients:
      - "digitalmars-d-ldc@puremagic.com"
    on_success: never
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#ldc"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: true
